# Generated by Django 3.0.8 on 2020-08-03 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='PK')),
                ('name', models.TextField()),
                ('sNum', models.TextField(unique=True)),
                ('pNum', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LectureBook',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('author', models.TextField()),
                ('lecture', models.TextField()),
                ('option', models.TextField()),
                ('isAvailable', models.BooleanField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='sNum')),
            ],
        ),
        migrations.CreateModel(
            name='LectureBookRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecturebookTitle', models.TextField()),
                ('ownerName', models.TextField()),
                ('receiverName', models.TextField()),
                ('option', models.TextField()),
                ('requestTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('isAccepted', models.BooleanField(default=False)),
                ('lecturebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecturebook.LectureBook')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owning', to=settings.AUTH_USER_MODEL, to_field='sNum')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiving', to=settings.AUTH_USER_MODEL, to_field='sNum')),
            ],
        ),
    ]
