# Generated by Django 3.0.8 on 2020-08-04 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sNum',
            field=models.TextField(max_length=10, unique=True),
        ),
    ]
