# Generated by Django 3.0.8 on 2020-07-30 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lecturebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturebook',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lecturebook',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='sNum'),
        ),
        migrations.CreateModel(
            name='LectureBookRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecturebookTitle', models.TextField()),
                ('ownerName', models.TextField()),
                ('receiverName', models.TextField()),
                ('option', models.TextField()),
                ('requestTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('isAccepted', models.BooleanField(default=False)),
                ('lecturebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecturebook.LectureBook')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owning', to=settings.AUTH_USER_MODEL, to_field='sNum')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiving', to=settings.AUTH_USER_MODEL, to_field='sNum')),
            ],
        ),
    ]
