# Generated by Django 3.0.8 on 2020-08-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturebook', '0002_auto_20200804_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sNum',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
