# Generated by Django 3.0.8 on 2020-07-30 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('culture', models.TextField()),
                ('major', models.TextField()),
                ('normal', models.TextField()),
                ('forLectures', models.TextField()),
                ('progressingMajor', models.TextField()),
                ('isLifeChecked', models.IntegerField()),
                ('studentNum', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditData', to=settings.AUTH_USER_MODEL, to_field='sNum')),
            ],
        ),
    ]
