# Generated by Django 3.0.8 on 2020-07-30 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditdata',
            old_name='culture',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='creditdata',
            name='forLectures',
        ),
        migrations.RemoveField(
            model_name='creditdata',
            name='isLifeChecked',
        ),
        migrations.RemoveField(
            model_name='creditdata',
            name='major',
        ),
        migrations.RemoveField(
            model_name='creditdata',
            name='normal',
        ),
        migrations.RemoveField(
            model_name='creditdata',
            name='progressingMajor',
        ),
        migrations.RemoveField(
            model_name='creditdata',
            name='studentNum',
        ),
    ]
